# Generated by Django 3.1.3 on 2020-11-30 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(verbose_name='biographie')),
                ('phone', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('birth_date', models.DateTimeField(verbose_name='date de naissance')),
                ('town', models.CharField(max_length=250)),
                ('sex', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
