# Generated by Django 3.1.3 on 2020-12-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201203_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
